<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (C) 2025-2026 the Jasper Server OS Authors
  ~ SPDX-License-Identifier: AGPL-3.0-or-later
  ~ Copyright (C) 2005-2023. Cloud Software Group, Inc. All Rights Reserved.
  ~ http://www.jaspersoft.com.
  ~
  ~ Unless you have purchased a commercial license agreement from Jaspersoft,
  ~ the following license terms apply:
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU Affero General Public License as
  ~ published by the Free Software Foundation, either version 3 of the
  ~ License, or (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  ~ GNU Affero General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program. If not, see <http://www.gnu.org/licenses/>.
  -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.jaspersoft.jasperserver</groupId>
        <artifactId>jasperserver-api</artifactId>
        <version>${buildArtifactVersionName}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.jaspersoft.jasperserver.api.common-ds</groupId>
    <artifactId>common-ds</artifactId>
    <name>Common Data Source API</name>
    <packaging>jar</packaging>
    <description>Used to keep Teiid dependencies away</description>

    <dependencies>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>${spring.version}</version>
        </dependency>

        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <version>${jakarta.annotation-api.version}</version>
        </dependency>

        <dependency>
            <groupId>com.jaspersoft.jasperserver.api.common</groupId>
            <artifactId>jasperserver-api-common</artifactId>
        </dependency>

        <dependency>
            <groupId>com.jaspersoft.jasperserver</groupId>
            <artifactId>jasperserver-dto</artifactId>
        </dependency>

        <dependency>
            <groupId>com.jaspersoft.jasperserver</groupId>
            <artifactId>jasperserver-jakarta-libs</artifactId>
            <type>pom</type>
        </dependency>

        <dependency>
            <groupId>org.jboss.teiid</groupId>
            <artifactId>teiid-engine</artifactId>
            <classifier>jakarta</classifier>
            <exclusions>
        		<exclusion>
            		<groupId>*</groupId>
		            <artifactId>*</artifactId>
        		</exclusion>
    		</exclusions>
        </dependency>
        <dependency>
            <groupId>jakarta.transaction</groupId>
            <artifactId>jakarta.transaction-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.resource</groupId>
            <artifactId>jakarta.resource-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jboss.teiid</groupId>
            <artifactId>teiid-runtime</artifactId>
            <classifier>jakarta</classifier>
            <exclusions>
        		<exclusion>
            		<groupId>*</groupId>
		            <artifactId>*</artifactId>
        		</exclusion>
    		</exclusions>
        </dependency>
        <dependency>
            <groupId>org.jboss.teiid</groupId>
            <artifactId>teiid-admin</artifactId>
            <classifier>jakarta</classifier>
            <exclusions>
        		<exclusion>
            		<groupId>*</groupId>
		            <artifactId>*</artifactId>
        		</exclusion>
    		</exclusions>
        </dependency>
        <dependency>
            <groupId>org.jboss.teiid</groupId>
            <artifactId>teiid-api</artifactId>
            <classifier>jakarta</classifier>
            <exclusions>
        		<exclusion>
            		<groupId>*</groupId>
		            <artifactId>*</artifactId>
        		</exclusion>
    		</exclusions>
        </dependency>
        <dependency>
            <groupId>org.jboss.teiid</groupId>
            <artifactId>teiid-common-core</artifactId>
            <classifier>jakarta</classifier>
            <exclusions>
        		<exclusion>
            		<groupId>*</groupId>
		            <artifactId>*</artifactId>
        		</exclusion>
    		</exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>${log4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>${log4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-1.2-api</artifactId>
            <version>${log4j.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.plugin.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>org.junit.platform</groupId>
                        <artifactId>junit-platform-surefire-provider</artifactId>
                        <version>${junit-platform-surefire-provider.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
</project>

